from .crypto import GTAIVCrypto, GTAIV_AES_KEY, GTAIV_KEY_SHA1, extract_aes_key
from .gtxd import (
    GTXD_SECTION,
    GtxdDependency,
    GtxdDocument,
    GtxdHierarchy,
    create_gtxd,
    load_gtxd,
)
from .img import IMG3_ENTRY_SIZE, IMG3_MAGIC, IMG3_VERSION, ImgArchive, ImgEntry, create_img, load_img
from .ide import IdeDocument, IdeEntry, IdeLine, create_ide, load_ide
from .materials import WbnMaterialType
from .model import (
    ModelAabb,
    ModelAsset,
    ModelBone,
    ModelBoundingSphere,
    ModelColor,
    ModelColorChannel,
    ModelCoordinateSystem,
    ModelLight,
    ModelLightType,
    ModelLod,
    ModelMaterial,
    ModelMaterialParameter,
    ModelMatrix4,
    ModelMesh,
    ModelObject,
    ModelParameterKind,
    ModelParameterValue,
    ModelPrimitive,
    ModelSkeleton,
    ModelTexCoordChannel,
    ModelTexture,
    ModelTextureFormat,
    ModelTextureKind,
    ModelTextureReference,
    ModelVector2,
    ModelVector3,
    ModelVector4,
)
from .nod import (
    NOD_HEADER_SIZE,
    NOD_HEURISTIC_SENTINEL,
    NOD_LINK_COUNT_MASK,
    NOD_LINK_COUNT_SHIFT,
    NOD_LINK_SIZE,
    NOD_NODE_FLAG_INFO,
    NOD_NODE_SIZE,
    NOD_PATH_WIDTH_SCALE,
    NOD_XY_SCALE,
    NOD_Z_SCALE,
    NodDocument,
    NodFlagConfidence,
    NodLink,
    NodNode,
    NodNodeFlagInfo,
    NodNodeFlags,
    NodNodeKind,
    NodVector3,
    combine_nod_graphs,
    explain_node_flags,
    load_nod,
    load_nod_graph,
)
from .path import (
    PathEdge,
    PathGraph,
    PathMetadataValue,
    PathNode,
    PathNodeId,
    PathNodeKey,
    PathNodeKind,
    PathSourceMetadata,
    PathVector3,
    combine_path_graphs,
)
from .rpf import (
    RPF2_MAGIC,
    RPF3_MAGIC,
    RPF_ENCRYPTED,
    RPF_HEADER_SIZE,
    RpfArchive,
    RpfDirectoryEntry,
    RpfEntry,
    RpfFileEntry,
    create_rpf,
    load_rpf,
)
from .rsc import (
    RSC5_HEADER_SIZE,
    RSC5_MAGIC,
    RSC5_PHYSICAL_BASE,
    RSC5_VIRTUAL_BASE,
    Rsc5Resource,
    rsc5_physical_size,
    rsc5_pointer_offset,
    rsc5_virtual_size,
)
from .shaders import (
    WDR_SHADER_DEFINITIONS,
    WDR_SHADER_PRESETS_BY_PROGRAM,
    WdrShaderDefault,
    WdrShaderDefaultKind,
    WdrShaderDefaultValue,
    WdrShaderDefinition,
    WdrShaderParameterName,
    WdrShaderPreset,
    WdrShaderProgram,
    find_wdr_shader_definition,
    find_wdr_shader_program,
)
from .wbd import WBD_DICTIONARY_SIZE, WBD_RESOURCE_VERSION, WbdDocument, WbdEntry, joaat, load_wbd
from .wbn import (
    WBN_BOUND_SIZE,
    WBN_BVH_GEOMETRY_SIZE,
    WBN_COMPOSITE_SIZE,
    WBN_GEOMETRY_SIZE,
    WBN_RESOURCE_VERSION,
    WbnAabb,
    WbnBound,
    WbnBoundType,
    WbnBvhGeometry,
    WbnBvhNode,
    WbnBvhSubTree,
    WbnBvhTree,
    WbnComposite,
    WbnDocument,
    WbnGeometry,
    WbnMaterial,
    WbnMaterialFlags,
    WbnMatrix,
    WbnPolygon,
    WbnVector3,
    WbnVector4,
    WbnVertex,
    load_wbn,
)
from .wdd import WDD_DICTIONARY_SIZE, WDD_RESOURCE_VERSION, WddDocument, WddEntry, load_wdd
from .wdr import (
    WDR_DRAWABLE_SIZE,
    WDR_GEOMETRY_SIZE,
    WDR_INDEX_BUFFER_SIZE,
    WDR_LIGHT_SIZE,
    WDR_LOD_SIZE,
    WDR_MODEL_SIZE,
    WDR_RESOURCE_VERSION,
    WDR_SHADER_PARAMETER_NAMES,
    WDR_SHADER_SIZE,
    WDR_VERTEX_BUFFER_SIZE,
    WDR_VERTEX_LAYOUT_SIZE,
    WdrBone,
    WdrBoneFlags,
    WdrBoneId,
    WdrDocument,
    WdrDrawable,
    WdrDrawableLod,
    WdrDrawableModel,
    WdrGeometry,
    WdrIndexBuffer,
    WdrLight,
    WdrLightType,
    WdrLodLevel,
    WdrMatrix4,
    WdrPrimitiveType,
    WdrShader,
    WdrShaderGroup,
    WdrShaderParameter,
    WdrSkeleton,
    WdrTextureReference,
    WdrVector2,
    WdrVector3,
    WdrVector4,
    WdrVertex,
    WdrVertexBuffer,
    WdrVertexElement,
    WdrVertexElementType,
    WdrVertexLayout,
    WdrVertexSemantic,
    load_wdr,
)
from .wtd import (
    RSC5_TEXTURE_DICTIONARY_SIZE,
    RSC5_TEXTURE_SIZE,
    WTD_RESOURCE_VERSION,
    Rsc5Texture,
    Rsc5TextureDictionary,
    Rsc5TextureFormat,
    WtdDocument,
    load_wtd,
    read_rsc5_texture_dictionary,
)
from .wft import (
    WFT_CHILD_SIZE,
    WFT_DRAWABLE_SIZE,
    WFT_FRAGMENT_SIZE,
    WFT_GROUP_SIZE,
    WFT_PHYSICS_ARCHETYPE_SIZE,
    WFT_RESOURCE_VERSION,
    WftChild,
    WftChildFlags,
    WftDampingKind,
    WftDocument,
    WftEventReferences,
    WftFragment,
    WftFragmentDrawable,
    WftFragmentFlags,
    WftGroup,
    WftGroupFlags,
    WftMatrix3x4,
    WftPhysicsArchetype,
    WftSelfCollision,
    load_wft,
)
from .wnv import (
    WNV_AABB_SCALE,
    WNV_COVER_POINT_SIZE,
    WNV_EDGE_SIZE,
    WNV_HEADER_SIZE,
    WNV_POLYGON_SIZE,
    WNV_QUADTREE_DATA_SIZE,
    WNV_QUADTREE_SIZE,
    WNV_QUANTIZED_SCALE,
    WNV_RESOURCE_VERSION,
    WNV_VERTEX_SIZE,
    WnvAabb,
    WnvCoverPoint,
    WnvDocument,
    WnvEdge,
    WnvEdgeFlags,
    WnvFlags,
    WnvMatrix,
    WnvPolygon,
    WnvPolygonFlags,
    WnvQuadTree,
    WnvQuadTreeData,
    WnvVector3,
    WnvVector4,
    WnvVertex,
    load_wnv,
)
from .wpl import (
    WPL_INSTANCE_FLAG_INFO,
    WPL_HEADER_SIZE,
    WPL_SECTION_SIZES,
    WPL_VERSION,
    WplBlock,
    WplCull,
    WplDocument,
    WplGarage,
    WplInstance,
    WplInstanceFlagInfo,
    WplInstanceFlags,
    WplLodCull,
    WplParkedCar,
    WplStrBig,
    WplTimeCycleModifier,
    WplZone,
    create_wpl,
    explain_instance_flags,
    load_wpl,
)
from .wpl_lod import (
    WplLodEdge,
    WplLodHierarchy,
    WplLodHierarchyError,
    WplLodIssue,
    WplLodIssueCode,
    WplLodNode,
    WplLodParentScope,
)

__version__ = "0.1.0"

__all__ = [
    "GTAIVCrypto", "GTAIV_AES_KEY", "GTAIV_KEY_SHA1", "GTXD_SECTION", "GtxdDependency",
    "GtxdDocument", "GtxdHierarchy", "IMG3_ENTRY_SIZE", "IMG3_MAGIC",
    "IMG3_VERSION", "IdeDocument", "IdeEntry", "IdeLine", "ImgArchive", "ImgEntry",
    "ModelAabb", "ModelAsset", "ModelBone", "ModelBoundingSphere",
    "ModelColor", "ModelColorChannel", "ModelCoordinateSystem", "ModelLight",
    "ModelLightType", "ModelLod", "ModelMaterial", "ModelMaterialParameter",
    "ModelMatrix4", "ModelMesh", "ModelObject", "ModelParameterKind",
    "ModelParameterValue", "ModelPrimitive", "ModelSkeleton", "ModelTexCoordChannel",
    "ModelTexture", "ModelTextureFormat", "ModelTextureKind", "ModelTextureReference",
    "ModelVector2", "ModelVector3", "ModelVector4", "NOD_HEADER_SIZE",
    "NOD_HEURISTIC_SENTINEL", "NOD_LINK_COUNT_MASK",
    "NOD_LINK_COUNT_SHIFT", "NOD_LINK_SIZE", "NOD_NODE_FLAG_INFO", "NOD_NODE_SIZE",
    "NOD_PATH_WIDTH_SCALE", "NOD_XY_SCALE", "NOD_Z_SCALE", "NodDocument",
    "NodFlagConfidence", "NodLink", "NodNode", "NodNodeFlagInfo", "NodNodeFlags",
    "NodNodeKind", "NodVector3", "PathEdge", "PathGraph", "PathMetadataValue",
    "PathNode", "PathNodeId", "PathNodeKey", "PathNodeKind", "PathSourceMetadata",
    "PathVector3",
    "RPF2_MAGIC", "RPF_ENCRYPTED", "RPF3_MAGIC", "RPF_HEADER_SIZE", "RSC5_HEADER_SIZE",
    "RSC5_MAGIC", "RSC5_PHYSICAL_BASE", "RSC5_TEXTURE_DICTIONARY_SIZE", "RSC5_TEXTURE_SIZE",
    "RSC5_VIRTUAL_BASE", "RpfArchive",
    "RpfDirectoryEntry", "RpfEntry", "RpfFileEntry", "Rsc5Resource", "Rsc5Texture",
    "Rsc5TextureDictionary", "Rsc5TextureFormat", "WBN_BOUND_SIZE",
    "WBN_BVH_GEOMETRY_SIZE", "WBN_COMPOSITE_SIZE", "WBN_GEOMETRY_SIZE",
    "WBD_DICTIONARY_SIZE", "WBD_RESOURCE_VERSION", "WBN_RESOURCE_VERSION", "WPL_HEADER_SIZE",
    "WbdDocument", "WbdEntry", "WbnAabb", "WbnBound", "WbnBoundType",
    "WbnBvhGeometry", "WbnBvhNode", "WbnBvhSubTree", "WbnBvhTree", "WbnComposite",
    "WbnDocument", "WbnGeometry", "WbnMaterial", "WbnMaterialFlags", "WbnMaterialType", "WbnMatrix",
    "WbnPolygon", "WbnVector3", "WbnVector4", "WbnVertex",
    "WDD_DICTIONARY_SIZE", "WDD_RESOURCE_VERSION", "WddDocument", "WddEntry",
    "WDR_DRAWABLE_SIZE", "WDR_GEOMETRY_SIZE", "WDR_INDEX_BUFFER_SIZE", "WDR_LIGHT_SIZE",
    "WDR_LOD_SIZE", "WDR_MODEL_SIZE", "WDR_RESOURCE_VERSION", "WDR_SHADER_PARAMETER_NAMES",
    "WDR_SHADER_SIZE", "WDR_VERTEX_BUFFER_SIZE", "WDR_VERTEX_LAYOUT_SIZE",
    "WDR_SHADER_DEFINITIONS", "WDR_SHADER_PRESETS_BY_PROGRAM", "WdrBone",
    "WdrBoneFlags", "WdrBoneId", "WdrDocument", "WdrDrawable", "WdrDrawableLod", "WdrDrawableModel",
    "WdrGeometry", "WdrIndexBuffer", "WdrLight", "WdrLightType", "WdrLodLevel",
    "WdrShaderDefault", "WdrShaderDefaultKind", "WdrShaderDefaultValue",
    "WdrShaderDefinition",
    "WdrShaderParameterName", "WdrShaderPreset", "WdrShaderProgram",
    "WdrMatrix4", "WdrPrimitiveType", "WdrShader", "WdrShaderGroup", "WdrShaderParameter", "WdrSkeleton",
    "WdrTextureReference", "WdrVector2", "WdrVector3", "WdrVector4", "WdrVertex",
    "WdrVertexBuffer", "WdrVertexElement", "WdrVertexElementType", "WdrVertexLayout",
    "WdrVertexSemantic", "WTD_RESOURCE_VERSION", "WtdDocument",
    "WFT_CHILD_SIZE", "WFT_DRAWABLE_SIZE", "WFT_FRAGMENT_SIZE", "WFT_GROUP_SIZE",
    "WFT_PHYSICS_ARCHETYPE_SIZE", "WFT_RESOURCE_VERSION", "WftChild", "WftChildFlags",
    "WftDampingKind", "WftDocument", "WftEventReferences", "WftFragment",
    "WftFragmentDrawable", "WftFragmentFlags", "WftGroup", "WftGroupFlags",
    "WftMatrix3x4", "WftPhysicsArchetype", "WftSelfCollision",
    "WNV_AABB_SCALE", "WNV_COVER_POINT_SIZE", "WNV_EDGE_SIZE", "WNV_HEADER_SIZE",
    "WNV_POLYGON_SIZE", "WNV_QUADTREE_DATA_SIZE", "WNV_QUADTREE_SIZE",
    "WNV_QUANTIZED_SCALE", "WNV_RESOURCE_VERSION", "WNV_VERTEX_SIZE", "WnvAabb",
    "WnvCoverPoint", "WnvDocument", "WnvEdge", "WnvEdgeFlags", "WnvFlags", "WnvMatrix",
    "WnvPolygon", "WnvPolygonFlags", "WnvQuadTree", "WnvQuadTreeData", "WnvVector3",
    "WnvVector4", "WnvVertex",
    "WPL_INSTANCE_FLAG_INFO", "WPL_SECTION_SIZES", "WPL_VERSION", "WplBlock", "WplCull",
    "WplDocument", "WplGarage", "WplInstance", "WplInstanceFlagInfo", "WplInstanceFlags",
    "WplLodCull", "WplLodEdge", "WplLodHierarchy", "WplLodHierarchyError", "WplLodIssue",
    "WplLodIssueCode", "WplLodNode", "WplLodParentScope", "WplParkedCar", "WplStrBig",
    "WplTimeCycleModifier", "WplZone",
    "combine_nod_graphs", "combine_path_graphs", "create_gtxd", "create_ide", "create_img", "create_rpf", "create_wpl", "joaat",
    "explain_instance_flags", "explain_node_flags", "find_wdr_shader_definition",
    "find_wdr_shader_program",
    "extract_aes_key", "load_ide", "load_img", "load_nod", "load_nod_graph", "load_rpf", "load_wbn",
    "load_gtxd", "load_wbd", "load_wdd", "load_wdr", "load_wft", "load_wnv", "load_wpl", "load_wtd", "read_rsc5_texture_dictionary",
    "rsc5_physical_size", "rsc5_pointer_offset", "rsc5_virtual_size",
]
